# Generated by Django 4.0.5 on 2023-11-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0002_alter_blogarticle_alt_img_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='autor_photo',
            field=models.ImageField(blank=True, default='', upload_to='blog_img', verbose_name='Фото автора (необяз. поле), имеется фото по умолчанию'),
        ),
    ]
