# Generated by Django 4.0.5 on 2023-11-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0004_blogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='img_alt',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='img_title',
        ),
    ]
