# Generated by Django 4.0.5 on 2023-10-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProductItem', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': '9. Отзывы'},
        ),
    ]
