# Generated by Django 4.0.5 on 2023-09-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_product_url',
            field=models.URLField(max_length=255, verbose_name='URL товара'),
        ),
    ]
