# Generated by Django 4.0.5 on 2023-02-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=255, verbose_name='Название категории товара для меню')),
                ('product_category_slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('product_category_is_published', models.BooleanField(default=True, verbose_name='Разрешить публикацию категории')),
                ('product_category_description', models.TextField(max_length=200, verbose_name='Описание страницы SEO (description)')),
                ('product_category_keywords', models.CharField(max_length=255, verbose_name='Ключевые слова SEO (keywordss)')),
                ('product_category_h1', models.CharField(max_length=255, verbose_name='Большой заголовок H1')),
                ('product_category_h2', models.CharField(max_length=255, verbose_name='Маленький заголовок H2')),
                ('product_category_img_main', models.ImageField(upload_to='category_img/', verbose_name='Фото для меню категории 210х140')),
                ('product_category_img_main_alt', models.CharField(max_length=80, verbose_name='Атрибут alt основного фото категории')),
                ('product_category_img_main_title', models.CharField(max_length=80, verbose_name='Атрибут title основного фото категории')),
                ('product_category_img_mobile', models.ImageField(upload_to='category_img/', verbose_name='Фото шапки для стр. категории - mobile 576х568')),
                ('product_category_img_mobile_horizontal', models.ImageField(upload_to='category_img/', verbose_name='Фото шапки  для стр. категории - mobile 768х568')),
                ('product_category_img_tablet', models.ImageField(upload_to='category_img/', verbose_name='Фото шапки для стр. категории - tablet 1200х550')),
                ('product_category_img_desktop', models.ImageField(upload_to='category_img/', verbose_name='Фото шапки для стр. категории - desktop 1440х760')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': '7. Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorName', models.CharField(max_length=255, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': '3. Цвета',
            },
        ),
        migrations.CreateModel(
            name='ProductFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fittingName', models.CharField(max_length=255, verbose_name='Фурнитура')),
            ],
            options={
                'verbose_name': 'Фурнитура',
                'verbose_name_plural': '5. Фурнитруа',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_group_name', models.CharField(max_length=255, verbose_name='Группа товара')),
                ('product_group_slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('product_group_is_published', models.BooleanField(default=True, verbose_name='Разрешить публикацию группы на главной странице')),
                ('product_group_short_name', models.CharField(default='sale', max_length=255, verbose_name='Короткое имя (sale, hot, new...)')),
            ],
            options={
                'verbose_name': 'Группа товара',
                'verbose_name_plural': '8. Группы товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductMakeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_time', models.CharField(max_length=255, verbose_name='Время изготовления')),
            ],
            options={
                'verbose_name': 'Время изготовления',
                'verbose_name_plural': '6. Время изготовления',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialName', models.CharField(max_length=255, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': '4. Материалы',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('product_is_published', models.BooleanField(default=True, verbose_name='Разрешить публикацию')),
                ('product_slug', models.SlugField(max_length=255, unique=True, verbose_name='URL (формирует автоматически из "Наименование товара")')),
                ('product_page_description', models.TextField(max_length=200, verbose_name='Описание страницы SEO (description)')),
                ('product_page_keywords', models.CharField(max_length=255, verbose_name='Ключевые слова SEO (keywordss)')),
                ('product_price', models.CharField(max_length=255, verbose_name='Цена')),
                ('product_old_price', models.CharField(blank=True, default=None, max_length=255, verbose_name='Старая цена')),
                ('product_size', models.CharField(max_length=255, verbose_name='Размер')),
                ('product_description', models.TextField(verbose_name='Описание')),
                ('product_img_main', models.ImageField(upload_to='product_item_img/', verbose_name='Основное фото товара 360х240')),
                ('product_img_main_alt', models.CharField(max_length=80, verbose_name='Атрибут alt основного фото товара')),
                ('product_img_main_title', models.CharField(max_length=80, verbose_name='Атрибут title основного фото товара')),
                ('product_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product_time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProductItem.productcategory', verbose_name='Категория')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProductItem.productcolor', verbose_name='Цвет')),
                ('product_fitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appProductItem.productfitting', verbose_name='Фурнитура')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProductItem.productgroup', verbose_name='Группа')),
                ('product_make_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProductItem.productmaketime', verbose_name='Время изготовления')),
                ('product_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProductItem.productmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': '1. Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='product_item_img/', verbose_name='Средное фото 570х380')),
                ('product_img_alt', models.CharField(max_length=80, verbose_name='Атрибут alt среднего фото')),
                ('product_img_title', models.CharField(max_length=80, verbose_name='Атрибут title среднего фото')),
                ('product_img_big', models.ImageField(upload_to='product_item_img/', verbose_name='Большое фото 1280х853')),
                ('product_img_big_alt', models.CharField(max_length=80, verbose_name='Атрибут alt большого фото')),
                ('product_img_big_title', models.CharField(max_length=80, verbose_name='Атрибут title большого фото')),
                ('img_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProductItem.productitem', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Картинки для конечной страницы товара',
                'verbose_name_plural': '2. Картинки для конечной страницы товара',
            },
        ),
    ]
